# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSBase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSBase

pod 'Alamofire', '~> 4.3’
pod 'SwiftyJSON', '~>3.1.1’
pod 'SQLite.swift', '~> 0.11.2'

end
