/**
 * Const
 *
 * @author : Archi-Edge
 * @copyright © 2016 LocoBee. All rights reserved.
 */


import UIKit

class Const: NSObject {

//  AE
    static let SERVER_URL = "http://59.106.210.145";
    
    
    static let BUNDLE_ID_REMOVE_ADS : String = "jp.co.locobee.app.hideadd13";
    
    // link api get location google
    static let URL_API_GOOGLE_GET_LOCATION = "http://maps.googleapis.com/maps/api/geocode/json?latlng=#location#&sensor=true&language=#language#"
    
    static let HIRAKAKUPRO_W3 = "HiraKakuPro-W3";
    static let HIRAKAKUPRO_W6 = "HiraKakuPro-W6";
    
    /* color define */
    static let COLOR_PRIMARY = 0xfed303;
    static let COLOR_WHITE = 0xffffff;
    
    /* Key user default */
    static let USER_DEFAULT_KEY_API_KEY = "token";
    static let USER_DEFAULT_KEY_DEVICE_TOKEN = "device_token";
    static let USER_DEFAULT_KEY_INFO_ACCOUNT = "info_account_user";
    static let USER_DEFAULT_KEY_BADGE = "info_badge";
    static let USER_DEFAULT_KEY_BADGE_WELCOME = "info_badge_welcome";
    static let USER_DEFAULT_KEY_PREMIUM_USER = "info_user_premium";
    static let USER_DEFAULT_KEY_INTRODUCTION_FIRST = "introduction_first";
    static let USER_DEFAULT_KEY_PREMIUM = "default_premium";
    
    /* Common */
    static let KEY_RESPONSE_DATA = "data";
    static let KEY_RESPONSE_UNREAD = "unread";
    // Admob
    static let APP_ID_ADMOB_BANNER = "ca-app-pub-9879574696135115~7083731381";
    static let UNIT_ID_ADMOB_BANNER = "ca-app-pub-9879574696135115/1037197785";
    static let UNIT_ID_ADMOB_NATIVE = "ca-app-pub-9879574696135115/2374330184";
    
    // Ads ADG
    static let LOCATION_ID_ADG = "45888";
    
    /* Key params api */
    static let KEY_PARAMS_API_KEY = "api_key";
    static let KEY_PARAMS_TOPIC_ID = "topic_id";
    static let KEY_PARAMS_MESSAGE = "message";
    static let KEY_PARAMS_TYPE = "type";
    static let KEY_PARAMS_FILE_NAME_IMAGE = "file_name";
    static let KEY_PARAMS_THUMBNAIL = "thumbnail";
    static let KEY_PARAMS_MESSAGE_ID = "message_id";
    static let KEY_PARAMS_OFFSET = "offset";
    static let KEY_PARAMS_LIMIT = "limit";
    static let KEY_PARAMS_LANGUAGE = "language";
    static let KEY_PARAMS_IS_LIKE = "like";
    static let KEY_PARAMS_PHONE_LANGUAGE = "phone_language";
    
    static let KEY_PARAMS_EMAIL = "email";
    static let KEY_PARAMS_PASSWORD = "password";
    static let KEY_PARAMS_LONGITUDE = "longitude";
    static let KEY_PARAMS_LATITUDE = "latitude";
    static let KEY_PARAMS_LOGIN_TYPE = "login_type";
    static let KEY_PARAMS_DEVICE_TOKEN = "device_token";
    static let KEY_PARAMS_FIRSTNAME = "first_name";
    static let KEY_PARAMS_LASTNAME = "last_name";
    static let KEY_PARAMS_AVATAR = "avatar";
    static let KEY_PARAMS_AVATAR_SMALL = "avatar_small";
    static let KEY_PARAMS_AVATAR_MEDIUM = "avatar_medium";
    static let KEY_PARAMS_COUNTRY = "country";
    static let KEY_PARAMS_FACEBOOK_ID = "facebook_id";
    
    static let KEY_PARAMS_ADDRESS = "address";
    static let KEY_PARAMS_INFOR = "introduction";
    static let KEY_PARAMS_BIRTHDAY = "birthday";
    static let KEY_PARAMS_SEX = "sex";
    
    static let KEY_PARAMS_OLDPASS = "old_password";
    static let KEY_PARAMS_NEWPASS = "password";
    static let KEY_PARAMS_USER_ID = "user_id";
    static let KEY_PARAMS_BLOCK_USER = "block";
    
    static let KEY_PARAMS_TOPIC_TITLE = "title";
    static let KEY_PARAMS_TOPIC_CATEGORY = "category";
    static let KEY_PARAMS_TOPIC_LIMIT_CATEGORY = "limit_category";
    static let KEY_PARAMS_TOPIC_LIMIT_TIME = "limit";
    static let KEY_PARAMS_TOPIC_CONTENT = "content";
    static let KEY_PARAMS_TOPIC_LANGUAGE = "language";
    static let KEY_PARAMS_TOPIC_ADDRESS = "address";
    static let KEY_PARAMS_UNREAD_TOPIC = "topic";
    static let KEY_PARAMS_UNREAD_NOTIFICAION = "notification";
    static let KEY_PARAMS_UNREAD_TOTAL = "total";
    
    static let KEY_RESPONSE_RESULT = "results";
    static let KEY_RESPONSE_ADDRESS_API_GOOGLE = "formatted_address";
    
    static let LOGIN_DEFAULT = 1;
    static let LOGIN_FACEBOOK = 2;
    static let VALUE_PARAMS_LIMIT = 20;
    static let MAX_LENGTH_FULL_NAME = 6;
    
    static let KEY_PARAMS_TYPING = "typing";
    
    static let KEY_PARAMS_SEND_TO = "send_to";
    
    static let KEY_PARAMS_PUSH_ID = "push_id";
    
    /* define url */
    static let URL_TERM = SERVER_URL + "/term?";
    static let URL_PRIVACY = SERVER_URL + "/privacy?";
    static let URL_NOTICE = SERVER_URL + "/news?";
    static let URL_HELP = SERVER_URL + "/help?";
    
    /* define key notification */
    static let KEY_NOTIFICATION_PUSH = NSNotification.Name(rawValue: "notification_push");
    static let KEY_NOTIFICATION_MESSAGE = NSNotification.Name(rawValue: "notification_message");
    static let KEY_NOTIFICATION_SET_BADGE_TAB = NSNotification.Name(rawValue: "notification_badge_tab");
    static let KEY_NOTIFICATION_SOCKET_NEW_CONNECT = NSNotification.Name(rawValue: "socket_new_connect");
    static let KEY_NOTIFICATION_ON_TYPING = NSNotification.Name(rawValue: "socket_on_typing");
    static let KEY_NOTIFICATION_ON_STOP_TYPING = NSNotification.Name(rawValue: "socket_on_stop_typing");
    static let KEY_NOTIFICATION_NEW_MESSAGE_USER = NSNotification.Name(rawValue: "socket_new_message_user");
    static let KEY_NOTIFICATION_DETAIL_UPDATE = NSNotification.Name(rawValue: "notification_detail_update");
    static let KEY_NOTIFICATION_RELOADS_TOP_WHEN_CREATE_TOPIC = NSNotification.Name(rawValue: "notification_reloads_tab_home_when_update_tab_home");
    static let KEY_NOTIFICATION_RELOADS_TOP_WHEN_ACTIVE_ACCOUNT_PREMIUM = NSNotification.Name(rawValue: "notification_reloads_tab_home_when_active_account_premium");
    static let KEY_NOTIFICATION_NETWORK = NSNotification.Name(rawValue: "notification_network");
    
    /* color define */
    static let COLOR_FED303 = 0xfed303;
    static let COLOR_FFFFFF = 0xffffff;
    static let COLOR_4E4A39 = 0x4e4a39;
    static let COLOR_F26262 = 0xf26262;
    static let COLOR_888888 = 0x888888;
    static let COLOR_46C39B = 0x46c39b;
    static let COLOR_BDBDBD = 0xbdbdbd;
    static let COLOR_F7F6F1 = 0xf7f6f1;
    static let COLOR_DRINK = 0xffa725;
    static let COLOR_FOOD = 0xf26262;
    static let COLOR_PLAY = 0x46c39b;
    static let COLOR_HELP = 0x2bb6e1;
    static let COLOR_PLACEHOLDER = 0xfff2cc;
    
    static let COLOR_PLACEHOLDER_SETTING = 0xbdbdbd;
    
    /* category define */
    
    static let TOPIC_CATEGORY_FOOD = 1;
    static let TOPIC_CATEGORY_DRINK = 2;
    static let TOPIC_CATEGORY_PLAY = 3;
    static let TOPIC_CATEGORY_HELP = 4;
    
    /* topic date type */
    static let TOPIC_DATE_TODAY = 1;
    static let TOPIC_DATE_TOMORROW = 2;
    static let TOPIC_DATE_SPECIFICATION = 3;

    static let CHAT_LOAD_MORE = 20;
    
    static let SEXCODE_UNKNOWN = 1;
    static let SEXCODE_MALE = 2;
    static let SEXCODE_FEMALE = 3;
    static let MALE = "male";
    static let FEMALE = "female";
    
    static let MALE_JA = "男性";
    static let FEMALE_JA = "女性";
    
    static let arrayCountries : [String] = [
        "AN",
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW",
    ];
    
    static let arrayLanguages : [String] = [
        "en",
        "ca",
        "ar",
        "fa",
        "en",
        "en",
        "sq",
        "hy",
        "ln",
        "en",
        "es",
        "en",
        "de",
        "en",
        "nl",
        "sv",
        "en",
        "hr",
        "en",
        "bn",
        "de",
        "fr",
        "bg",
        "ar",
        "fr",
        "fr",
        "fr",
        "en",
        "en",
        "es",
        "en",
        "pt",
        "en",
        "dz",
        "en",
        "en",
        "be",
        "en",
        "en",
        "en",
        "fr",
        "fr",
        "fr",
        "de",
        "fr",
        "en",
        "es",
        "agq",
        "zh",
        "es",
        "es",
        "es",
        "kea",
        "nl",
        "en",
        "el",
        "cs",
        "de",
        "ar",
        "da",
        "en",
        "es",
        "ar",
        "es",
        "et",
        "ar",
        "ar",
        "ar",
        "ca",
        "am",
        "fi",
        "en",
        "en",
        "en",
        "fo",
        "br",
        "fr",
        "en",
        "en",
        "ka",
        "fr",
        "en",
        "ak",
        "en",
        "kl",
        "en",
        "fr",
        "fr",
        "es",
        "el",
        "en",
        "es",
        "en",
        "pt",
        "en",
        "zh",
        "en",
        "es",
        "hr",
        "fr",
        "hu",
        "in",
        "en",
        "ar",
        "en",
        "as",
        "en",
        "ar",
        "fa",
        "is",
        "it",
        "en",
        "en",
        "ar",
        "ja",
        "dav",
        "ru",
        "km",
        "en",
        "ar",
        "en",
        "ko",
        "ko",
        "ar",
        "en",
        "ru",
        "lo",
        "ar",
        "en",
        "de",
        "si",
        "en",
        "en",
        "lt",
        "de",
        "lv",
        "ar",
        "ar",
        "fr",
        "ro",
        "en",
        "fr",
        "en",
        "en",
        "mk",
        "bm",
        "my",
        "en",
        "zh",
        "en",
        "fr",
        "ar",
        "en",
        "en",
        "en",
        "en",
        "en",
        "es",
        "ta",
        "mgh",
        "af",
        "fr",
        "dje",
        "en",
        "en",
        "es",
        "nl",
        "nb",
        "ne",
        "en",
        "en",
        "en",
        "ar",
        "es",
        "es",
        "fr",
        "en",
        "en",
        "en",
        "pl",
        "en",
        "en",
        "en",
        "ar",
        "pt",
        "en",
        "es",
        "ar",
        "fr",
        "ro",
        "en",
        "ru",
        "fr",
        "ar",
        "en",
        "en",
        "ar",
        "sv",
        "en",
        "en",
        "sl",
        "en",
        "sk",
        "en",
        "it",
        "dyo",
        "ar",
        "nl",
        "en",
        "pt",
        "es",
        "nl",
        "ar",
        "en",
        "en",
        "ar",
        "en",
        "ee",
        "th",
        "en",
        "en",
        "pt",
        "en",
        "ar",
        "en",
        "tr",
        "en",
        "en",
        "zh",
        "asa",
        "ru",
        "cgg",
        "en",
        "chr",
        "es",
        "en",
        "en",
        "en",
        "es",
        "en",
        "en",
        "vi",
        "en",
        "en",
        "en",
        "ar",
        "fr",
        "af",
        "bem",
        "en",
    ];
    
    static let arrayCountryNameFb : [String] = [
        "Netherlands Antilles",
        "Andorra",
        "United Arab Emirates",
        "Afghanistan",
        "Antigua",
        "Anguilla",
        "Albania",
        "Armenia",
        "Angola",
        "Antarctica",
        "Argentina",
        "American Samoa",
        "Austria",
        "Australia",
        "Aruba",
        "Aland Islands",
        "Azerbaijan",
        "Bosnia and Herzegovina",
        "Barbados",
        "Bangladesh",
        "Belgium",
        "Burkina Faso",
        "Bulgaria",
        "Bahrain",
        "Burundi",
        "Benin",
        "Saint BarthÈlemy",
        "Bermuda",
        "Brunei",
        "Bolivia",
        "Bonaire, Sint Eustatius and Saba",
        "Brazil",
        "The Bahamas",
        "Bhutan",
        "Bouvet Island",
        "Botswana",
        "Belarus",
        "Belize",
        "Canada",
        "Cocos (Keeling) Islands",
        "Democratic Republic of the Congo",
        "Central African Republic",
        "Republic of the Congo",
        "Switzerland",
        "Côte d’Ivoire",
        "Cook Islands",
        "Chile",
        "Cameroon",
        "China",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Cape Verde",
        "Curaçao",
        "Christmas Island",
        "Cyprus",
        "Czech Republic",
        "Germany",
        "Djibouti",
        "Denmark",
        "Dominica",
        "Dominican Republic",
        "Algeria",
        "Ecuador",
        "Estonia",
        "Egypt",
        "Western Sahara",
        "Eritrea",
        "Spain",
        "Ethiopia",
        "Finland",
        "Fiji",
        "Falkland Islands",
        "Federated States of Micronesia",
        "Faroe Islands",
        "France",
        "Gabon",
        "United Kingdom",
        "Grenada",
        "Georgia",
        "French Guiana",
        "Guernsey",
        "Ghana",
        "Gibraltar",
        "Greenland",
        "The Gambia",
        "Guinea",
        "Guadeloupe",
        "Equatorial Guinea",
        "Greece",
        "South Georgia and the South Sandwich Islands",
        "Guatemala",
        "Guam",
        "Guinea-Bissau",
        "Guyana",
        "Hong Kong",
        "Heard Island and McDonald Islands",
        "Honduras",
        "Croatia",
        "Haiti",
        "Hungary",
        "Indonesia",
        "Ireland",
        "Israel",
        "Isle Of Man",
        "India",
        "British Indian Ocean Territory",
        "Iraq",
        "Iran",
        "Iceland",
        "Italy",
        "Jersey",
        "Jamaica",
        "Jordan",
        "Japan",
        "Kenya",
        "Kyrgyzstan",
        "Cambodia",
        "Kiribati",
        "Comoros",
        "Saint Kitts and Nevis",
        "North Korea",
        "South Korea",
        "Kuwait",
        "Cayman Islands",
        "Kazakhstan",
        "Laos",
        "Lebanon",
        "St. Lucia",
        "Liechtenstein",
        "Sri Lanka",
        "Liberia",
        "Lesotho",
        "Lithuania",
        "Luxembourg",
        "Latvia",
        "Libya",
        "Morocco",
        "Monaco",
        "Moldova",
        "Montenegro",
        "Saint Martin",
        "Madagascar",
        "Marshall Islands",
        "Macedonia",
        "Mali",
        "Myanmar",
        "Mongolia",
        "Macau",
        "Northern Mariana Islands",
        "Martinique",
        "Mauritania",
        "Montserrat",
        "Malta",
        "Mauritius",
        "Maldives",
        "Malawi",
        "Mexico",
        "Malaysia",
        "Mozambique",
        "Namibia",
        "New Caledonia",
        "Niger",
        "Norfolk Island",
        "Nigeria",
        "Nicaragua",
        "Netherlands",
        "Norway",
        "Nepal",
        "Nauru",
        "Niue",
        "New Zealand",
        "Oman",
        "Panama",
        "Peru",
        "French Polynesia",
        "Papua New Guinea",
        "Philippines",
        "Pakistan",
        "Poland",
        "Saint Pierre and Miquelon",
        "Pitcairn",
        "Puerto Rico",
        "Palestine",
        "Portugal",
        "Palau",
        "Paraguay",
        "Qatar",
        "Réunion",
        "Romania",
        "Serbia",
        "Russia",
        "Rwanda",
        "Saudi Arabia",
        "Solomon Islands",
        "Seychelles",
        "Sudan",
        "Sweden",
        "Singapore",
        "Saint Helena",
        "Slovenia",
        "Svalbard and Jan Mayen",
        "Slovakia",
        "Sierra Leone",
        "San Marino",
        "Senegal",
        "Somalia",
        "Suriname",
        "South Sudan",
        "Sao Tome and Principe",
        "El Salvador",
        "Sint Maarten",
        "Syria",
        "Swaziland",
        "Turks and Caicos Islands",
        "Chad",
        "French Southern Territories",
        "Togo",
        "Thailand",
        "Tajikistan",
        "Tokelau",
        "Timor-Leste",
        "Turkmenistan",
        "Tunisia",
        "Tonga",
        "Turkey",
        "Trinidad and Tobago",
        "Tuvalu",
        "Taiwan",
        "Tanzania",
        "Ukraine",
        "Uganda",
        "United States Minor Outlying Islands",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vatican City",
        "Saint Vincent and the Grenadines",
        "Venezuela",
        "British Virgin Islands",
        "US Virgin Islands",
        "Vietnam",
        "Vanuatu",
        "Wallis and Futuna",
        "Samoa",
        "Yemen",
        "Mayotte",
        "South Africa",
        "Zambia",
        "Zimbabwe",
    ]
}
