source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Locozap' do
    pod 'Alamofire', '~> 4.2.0’
    pod 'SwiftyJSON', '~>3.1.1’
    pod 'Socket.IO-Client-Swift', '~> 8.2.0’
    pod 'AlamofireImage', '~> 3.2.0'
    pod 'DatePickerDialog'
    pod 'ObjectMapper', '~> 2.2.1'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Firebase/Messaging'
    pod 'TTTAttributedLabel'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'IgaworksCore'
    pod 'AdBrix'
    pod 'AdPopcornOfferwall'
    pod 'AdPopcornDA'
    pod 'IgaworksCommerce'
    pod 'IgaworksCoupon'
    pod 'IgaworksNanoo'
    pod 'LiveOps'
end
